public class Test1
{

    //Sync test with git
    public String getTest() {
        return system.label.COMM_Test;
    }

    public Test1()
    {
      //Jaysukh patel changed and added comment
    }
    public string test()
    {
        System.debug('Test');
        return system.label.COMM_Test;
    } 
    public string getGit()
    {
       // please return the value dynamically
       return 'git';
    }
    
}
